name: Bug report
description: Create a report to help us address issues you are facing with the app.
title: "[BUG] "
labels: [bug]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Lawnchair's issue tracker is maintained on a best-effort basis — due to limited resources, we do not guarantee that all issues will be triaged or checked by the developers.
        > If you wish to help triage Lawnchair's issues, visit [#4232](https://github.com/LawnchairLauncher/lawnchair/issues/4232) for more information.
        
        Thanks for taking the time to file this issue! Here are a few things to do before submitting:
        1. Make sure you're on the [latest **nightly** version](https://github.com/LawnchairLauncher/lawnchair#development-builds) of the app.
        2. [Read the FAQ](https://lawnchair.app/faq) to check if it's one of the common issues you can encounter in the launcher; if it is, please don't create an issue about it.
        3. Search through **both** [open and closed issues](https://github.com/LawnchairLauncher/lawnchair/issues?q=is%3Aissue+sort%3Aupdated-desc+) for your bug.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug. Be specific on what steps you need to do to encounter this bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    id: device-info
    attributes:
      label: Device information
      description: Provide details about your device, OS, app version, etc.
      placeholder: |
        - Device: Google Pixel 9
        - OS: stock Android 12.0
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App version
      description: Open Lawnchair settings > About to view the app version. On nightly builds, long-press the version name and paste the GitHub link here.
      placeholder: |
        14 Beta 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: If this is a crash report, you can paste or link the crash message in here.
    validations:
      required: false
